name: ruff

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-slim
    
    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@v10.0.1
      with:
        activate-environment: true

    - run: uv sync --locked
    - uses: astral-sh/ruff-action@v4.1.0
    - name: Analysing the code with ty
      run: uv run ty check
